semi: false
singleQuote: true
trailingComma: all
arrowParens: always
importOrder:
  - "<THIRD_PARTY_MODULES>"
  - "^@[/]"
  - "^[./]"
importOrderSeparation: true
importOrderParserPlugins:
  - "typescript",
  - "classProperties",
  - "decorators-legacy"

