# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '19.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run test:azure
    displayName: 'npm install and output coverage'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml
