# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  jar_version: 3.0.41

jobs:
  - job : 'lint_and_test'
    displayName: 'Run lint and tests'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '19.x'
        displayName: 'Install Node.js'

      - script: |
          npm install
        displayName: 'Install project dependency'

      - script: |
          npm run lint
        displayName: 'Lint'

      - script: |
          npm run test:azure
        displayName: 'Test and generate coverage report'

      #publish the tests results
      - task: PublishTestResults@2
        displayName: 'Publish test results '
        inputs:
          testResultsFiles: $(System.DefaultWorkingDirectory)/junit.xml
        condition: succeededOrFailed()

      #publish code coverage reports in cobertura format
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish code coverage report'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml


  - job: 'build_client_typescript_axios'
    displayName: 'Build client code for typescript axios'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '19.x'
        displayName: 'Install Node.js'

      - script: |
          npm install
        displayName: 'Install project dependency'

      - script: |
          npx ts-node scripts/doc-gen.ts
        displayName: 'Generate swagger.json'

      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '11'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
        displayName: 'Build client code for typescript axios'
      - script: |
          java -version
          wget https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/$(jar_version)/swagger-codegen-cli-$(jar_version).jar -O swagger-codegen-cli.jar
          java -jar swagger-codegen-cli.jar generate \
            -l typescript-axios \
            -i dist/swagger.json -o ./gen

      - task: PublishPipelineArtifact@1
        inputs:
          displayName: 'Publish artifacts'
          artifactName: 'client-typescript-axios'
          targetPath: $(Build.SourcesDirectory)/gen

